[package]
name = "polkadot-primitives-test-helpers"
version = "0.9.25"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
sp-keyring = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/jakehemmerle/substrate", default-features = false , branch = "8805-ed25519-zebra" }
sp-runtime = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }
polkadot-primitives = { path = "../" }
rand = "0.8.5"
