[package]
name = "test-parachains"
version = "0.9.25"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Integration tests using the test-parachains"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }

adder = { package = "test-parachain-adder", path = "adder" }
halt = { package = "test-parachain-halt", path = "halt" }

[dev-dependencies]
sp-core = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }

[features]
default = ["std"]
std = ["adder/std", "halt/std"]
