[package]
name = "remote-ext-tests-bags-list"
version = "0.9.25"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
polkadot-runtime = { path = "../../../runtime/polkadot" }
kusama-runtime = { path = "../../../runtime/kusama" }
westend-runtime = { path = "../../../runtime/westend" }
polkadot-runtime-constants = { path = "../../../runtime/polkadot/constants" }
kusama-runtime-constants = { path = "../../../runtime/kusama/constants" }
westend-runtime-constants = { path = "../../../runtime/westend/constants" }

pallet-bags-list-remote-tests = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }
sp-tracing = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }
frame-system = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }
sp-core = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }

clap = { version = "3.1", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.18.2", features = ["macros"] }
