[package]
name = "polkadot-voter-bags"
version = "0.9.25"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
clap = { version = "3.1", features = ["derive"] }

generate-bags = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }
sp-io = { git = "https://github.com/jakehemmerle/substrate", branch = "8805-ed25519-zebra" }

westend-runtime = { path = "../../runtime/westend" }
kusama-runtime = { path = "../../runtime/kusama" }
polkadot-runtime = { path = "../../runtime/polkadot" }
